service: api

provider:
  name: aws
  runtime: nodejs12.x

functions:
  payment-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
